routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('Auth/login');
});

// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::resource('/marz',"MarzController");
Route::resource('/balance',"BalanceController");
Route::resource('/gumrgpayment',"GumrgPaymenyController");

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

Route::get('/customers', 'CustomerController@index')->name('customers');
Route::get('/customers/search', 'CustomerController@search')->name('customers.search');
Route::get('/gumrg/search', 'GumrgController@search')->name('gumrgs.search');
Route::get('/gumrg/search_customer', 'GumrgController@search_customer')->name('gumrgs.search_customer');
Route::get('/gumrg/insertContract', 'GumrgController@insertContract')->name('gumrgs.insertContract');
Route::get('/gumrg/showContract', 'GumrgController@showContract')->name('gumrgs.showContract');
Route::get('/gumrg/action', 'GumrgController@action')->name('gumrg.action');
Route::get('/naql', 'GumrgController@naql')->name('naql');
// Route::get('/courses', 'courseController@store')->name('courses');
// Route::get('/courses', 'Courses@index')->name('home');
Route::resource('/customers',"CustomerController");
Route::resource('/gumrgs',"GumrgController");
Route::resource('/colors',"ColorController");
Route::resource('/cars',"CarsController");
Route::resource('/payments',"PaymentController");
Route::get('/payment', 'PaymentController@search')->name('payments.search');
Route::get('/invoice/{id}', 'PaymentController@invoice')->name('payments.invoice');
Route::resource('xawanQasa', 'XawanQasaController');
Route::get('/xawanQasas', 'XawanQasaController@search')->name('xawanQasa.search');
Route::resource('qasa', 'QasaController');
Route::get('/qasas', 'QasaController@search')->name('qasa.search');
// Route::resource('/courses',"courseController");
// Auth::routes();
Route::resource('roles', 'RoleController');
Route::resource('users', 'UserController');
Route::get('/users/action', 'UserController@action')->name('users.action');

Route::resource('permissions', 'PermissionController');

Route::get('/home', 'HomeController@index')->name('home');

app/XawanQasa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class XawanQasa extends Model
{
    public function qasa() {
        return $this->hasMany('App\XawanQasa');
    }

}

app/Http/Controllers/XawanQasaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\XawanQasa;
class XawanQasaController extends Controller
{
       /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $i=0;
        $XawanQasa = XawanQasa::paginate(10);
        return view('xawanQasa.index',["XawanQasa"=>$XawanQasa,"i"=>$i]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }
    public function search(Request $request)
    {
        //
        $search = $request->input("search");
        $obj  = XawanQasa::where('name','like','%'.$search.'%')->paginate(10);
        $i=0;
        return view("xawanQasa.index",['XawanQasa'=>$obj,'i'=>$i]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
          //
        $obj = new XawanQasa();
        $obj->name=$request->input('name');
        $obj->number=$request->input('phone');
        $obj->address=$request->input('address');
        $obj->save();
        return redirect(route('xawanQasa.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $XawanQasa = XawanQasa::find($id);
        // $XawanQasa = XawanQasa::all();
        return view('xawanQasa.edit')->with('XawanQasa',$XawanQasa);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $obj=XawanQasa::find($id);
        $obj->name= $request->input("name");
        $obj->number= $request->input("phone");
        $obj->address= $request->input("address");
        $obj->save();
        return redirect(route('xawanQasa.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $xawanQasa = XawanQasa::findOrFail($id); 
        $xawanQasa->delete();

        return redirect()->route('xawanQasa.index');
    }
}

resources/views/xawanQasa/edit.blade.php
@extends('adminlte::page')

@section('title', 'Hawras-Cars')

@section('content_header')
    <!-- <h1>Customer View</h1> -->
@stop

@section('content')
  
<div class="box">
            <div class="box-header">
              <h3 class="box-title">Customers</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box box-danger">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Customer</h3>
            </div>
            <form action="{{ route('xawanQasa.update',$XawanQasa->id) }}" method="POST">
      	{{csrf_field()}}
        <input type="hidden" name="_method" value="PUT">
            <div class="box-body">
              <div class="row">
                <div class="col-xs-2">
                  <input type="text" name="name" class="form-control" placeholder="ناو" value="{{$XawanQasa->name}}">
                </div>
                <div class="col-xs-3">
                  <input type="text" name="phone" class="form-control" placeholder="ژ.ته‌له‌فۆن" value="{{$XawanQasa->number}}">
                </div>
                <div class="col-xs-4">
                  <input type="text" name="address" class="form-control" placeholder="ناونیشان" value="{{$XawanQasa->address}}">
                </div>
                <div class="col-xs-2">
                  <button type="submit" class="btn btn-block btn-lg btn-success btn-lg">گۆرین</button>
                </div>
              </div>
            </div>
        </form>
            <!-- /.box-body -->
          </div>
           
            <!-- /.box-body -->
          </div>
@stop

resources/views/xawanQasa/index.blade.php
@extends('adminlte::page')

@section('title', 'Hawras-Cars')

@section('content_header')
@stop

@section('content')
  
<div class="box">
            <div class="box-header">
                <h1 style="text-align: center">خاوه‌ن قاصه‌كان</h1>
                  <div class="box-header with-border">
                      <div class="box-tools">
                          <form method="get" action="{{ route('xawanQasa.search') }}">
                          <div class="input-group input-group-sm" style="width: 150px;">
                            
                            <input type="text" name="search" class="form-control pull-right" placeholder="Search">
          
                            <div class="input-group-btn">
                              <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                          </div>
                          </form>
                        </div>
                  </div>
            </div>
            <br>
            <!-- /.box-header -->
            <div class="box box-danger">
            <form action="{{ route('xawanQasa.store') }}" method="post">
      	{{csrf_field()}}
            <div class="box-body">
              <div class="row">
                <div class="col-xs-2">
                  <input type="text" name="name" class="form-control" placeholder="ناو">
                </div>
                <div class="col-xs-3">
                  <input type="text" name="phone" class="form-control" placeholder="ژ.ته‌له‌فۆن">
                </div>
                <div class="col-xs-4">
                  <input type="text" name="address" class="form-control" placeholder="ناونیشان">
                </div>
                <div class="col-xs-2">
                  <button type="submit" class="btn btn-block btn-lg btn-success btn-lg">زیادكردن</button>
                </div>
              </div>
            </div>
        </form>
            <!-- /.box-body -->
          </div>
            <div class="box-body table-responsive no-padding table-bordered">
              <table class="table table-hover">
                <tbody><tr>
                  <th>#</th>
                  <th>ناو </th>
                  <th>ژماره‌ی مۆبایل</th>
                  <th>ناونیشان</th>
                  <th>Edit</th>
                </tr>
                 @foreach($XawanQasa as $c)
				    <tr>
				      <th scope="row">{{++$i}}</th>
				      <td>{{$c->name}}</td>
				      <td>{{$c->number}}</td>
				      <td>{{$c->address}}</td>
				      <td><form method="GET"action="{{ route('xawanQasa.edit',$c->id) }}">
                  {{ csrf_field() }}

                  <div class="form-group">
                      <input type="submit" class="btn btn-warning btn-xs " value="نوێكردنه‌وه‌" >
    
                  </div>
                        </form>
                        <td><form method="post" action="{{ route('xawanQasa.destroy',$c->id) }}" >
                                {{ csrf_field() }} 
                                <input type="hidden" name="_method" value="DELETE"  >
                                <button class="btn btn-danger btn-xs" onclick="return confirm('دڵنیایت له‌ سڕینه‌وه‌؟')">سڕینه‌وه‌</button>
                            </form>
                    </td>
				      </tr>
				      @endforeach

              </tbody></table>
            </div>
            <div class="text-center">
            {{ $XawanQasa->appends(Request::all())->render()}}
            </div>
            <!-- /.box-body -->
          </div>
@stop