routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('Auth/login');
});

// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::resource('/marz',"MarzController");
Route::resource('/balance',"BalanceController");
Route::resource('/gumrgpayment',"GumrgPaymenyController");

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

Route::get('/customers', 'CustomerController@index')->name('customers');
Route::get('/customers/search', 'CustomerController@search')->name('customers.search');
Route::get('/gumrg/search', 'GumrgController@search')->name('gumrgs.search');
Route::get('/gumrg/search_customer', 'GumrgController@search_customer')->name('gumrgs.search_customer');
Route::get('/gumrg/insertContract', 'GumrgController@insertContract')->name('gumrgs.insertContract');
Route::get('/gumrg/showContract', 'GumrgController@showContract')->name('gumrgs.showContract');
Route::get('/gumrg/action', 'GumrgController@action')->name('gumrg.action');
Route::get('/naql', 'GumrgController@naql')->name('naql');
// Route::get('/courses', 'courseController@store')->name('courses');
// Route::get('/courses', 'Courses@index')->name('home');
Route::resource('/customers',"CustomerController");
Route::resource('/gumrgs',"GumrgController");
Route::resource('/colors',"ColorController");
Route::resource('/cars',"CarsController");
Route::resource('/payments',"PaymentController");
Route::get('/payment', 'PaymentController@search')->name('payments.search');
Route::get('/invoice/{id}', 'PaymentController@invoice')->name('payments.invoice');
Route::resource('xawanQasa', 'XawanQasaController');
Route::get('/xawanQasas', 'XawanQasaController@search')->name('xawanQasa.search');
Route::resource('qasa', 'QasaController');
Route::get('/qasas', 'QasaController@search')->name('qasa.search');
// Route::resource('/courses',"courseController");
// Auth::routes();
Route::resource('roles', 'RoleController');
Route::resource('users', 'UserController');
Route::get('/users/action', 'UserController@action')->name('users.action');

Route::resource('permissions', 'PermissionController');

Route::get('/home', 'HomeController@index')->name('home');

app/Payments.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payments extends Model
{
    //
    public function Customers() {
        return $this->belongsTo('App\Customers','customer_id');
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Payments;
use App\Customers;
use DB;
class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $customers = Customers::all();
        $payments = Payments::all();
        $i=0;
        // $pay = Payments::all()
        //     ->join('Customers','customers.id','=','payments.customer_id')
        //     ->groupBy('customers.name')
        //     ->map(function ($m) {
        //         return $m->sum('amount');
        //     });
        $pay = DB::table('payments')
       ->join('customers', 'customers.id', '=', 'payments.customer_id')
       ->select('customers.name','customers.id', DB::raw('sum(payments.amount) as total '))
       ->groupBy(['customers.name','customers.id'])
       ->get();

       $gumrg = DB::table('gumrgs')
       ->join('customers', 'customers.id', '=', 'gumrgs.customer_id')
       ->select('customers.name','customers.id', DB::raw('sum(gumrgs.total) as total '))
       ->groupBy(['customers.name','customers.id'])
       ->get();
       foreach($gumrg as $g)
       {
        foreach ($pay as $p) {
            if($p->id == $g->id)
            {
                $g->pay= $p->total;
            }
            # code...
        }
       }
        return view('payments.payment',['customers'=>$customers, 'payments'=>$payments,'i'=>$i,'pay'=>$pay,'gumrg'=>$gumrg]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $obj = new Payments();
        $obj->amount=$request->input('amount');
        $obj->note=$request->input('note');
        $obj->date=$request->input('date');
        $obj->customer_id=$request->input('customer_id');
        $obj->save();
        return redirect(route('payments.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
         $payment = Payments::where('customer_id','=',$id)->get();
         $customers = Customers::all();
         $customer = Customers::find($id);
         $i=0;
         return view('payments.detail',['payment'=>$payment,'customers'=>$customers,'customer'=>$customer,'i'=>$i]);
    }
    public function search(Request $request)
    {
        //
       $customers = Customers::all();
        $payments = Payments::all();
        $i=0;

        $pay = DB::table('payments')
       ->join('customers', 'customers.id', '=', 'payments.customer_id')
       ->select('customers.name','customers.id', DB::raw('sum(payments.amount) as total '))
       ->groupBy(['customers.name','customers.id'])
       ->get();

       $selected=$request->input("search");
       $gumrg = DB::table('gumrgs')
       ->join('customers', 'customers.id', '=', 'gumrgs.customer_id')
       ->select('customers.name','customers.id', DB::raw('sum(gumrgs.total) as total '))
       ->groupBy(['customers.name','customers.id'])
       ->having('customers.id','=',$selected)
       ->get();
       foreach($gumrg as $g)
       {
        foreach ($pay as $p) {
            if($p->id == $g->id)
            {
                $g->pay= $p->total;
            }
            # code...
        }
       }
        return view('payments.payment',['customers'=>$customers, 'payments'=>$payments,'i'=>$i,'pay'=>$pay,'gumrg'=>$gumrg,'selected'=>$selected]);
            }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
         $payment = Payments::find($id);
        $customers = Customers::all();
        return view('payments.edit',['payment'=>$payment,'customers'=>$customers]);
    }

    public function invoice($id)
    {
        //
         $payment = Payments::find($id);
        $customer = Customers::find($payment->customer_id);
        return view('payments.invoice',['payment'=>$payment,'customer'=>$customer]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
         $obj=Payments::find($id);
        $obj->amount= $request->input("amount");
        $obj->date= $request->input("date");
        $obj->note= $request->input("note");
        $obj->customer_id= $request->input("customer_id");
        $obj->save();
        return redirect(route('payments.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
          error_log('Some message here.');
        $gumrg = Payments::findOrFail($id);
        $gumrg->delete();
        \Session::flash('flash_message_delete','Payment successfully deleted.');

        return redirect(route('payments.index'));

    }
}

resources/views/payments/detail.blade.php
@extends('adminlte::page')

@section('title', 'Hawras-Cars')

@section('content_header')
    <h1 class="text-center" >پاره‌دانه‌كانی {{ $customer->name }}</h1>
@stop
@section('content')
<style>
#wrapper2 {
    width: 80px;
    /*border: 1px solid black;*/
    overflow: hidden; /* will contain if #first is longer than #second */
}
#first {
    width: 40px;
    float:left; /* add this */
    /*border: 1px solid red;*/
}
#second {
  width: 40px;
    /*border: 1px solid green;*/
    overflow: hidden; /* if you don't want #second to wrap below #first */
}
</style>
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#insert-modal">
                <i class="fa fa-edit"></i>
              </button>
<table class="table table-respinsive table-hover table-fixed text-nowrap table-bordered">
    <thead>
        <tr class="row">
            <th> تێبینی </th>
            <th>به‌روار </th>
            <th>$ پاره‌دان</th>
            <th>#</th>
            <th>Edit</th>
            <th>وه‌سل</th>
        </tr>
    </thead>
    <tbody>
        @foreach($payment as $p)
            <tr class="row">
                <td>
                   {{$p->note}}
                </td>
                <td>
                   {{ $p->date }}
                </td>
                <td>
                   $ {{ $p->amount }}
                </td>
                
                <td>{{ ++$i }}
                </td>
                <td><div id="wrapper2">
                        <div id="first">
                            <form method="GET"action="{{ route('payments.edit',$p->id) }}">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-primary btn-circle btn-xs" data-toggle="modal" data-target="#edit-modal" > edit 
                                  <!-- <i class="fa fa-times"></i> -->
                            </button>
                                    </form>
                        </div>
                        <div id="second">
                            <form method="POST" action="/payments/{{$p->id}}">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}

                               <button type="submit" class="btn btn-danger btn-circle btn-xs" onclick="return confirm('Are you sure?')">
                                <i class="fa fa-times"></i>
                                </button>
                        </form>
                        </div>
                    </div>
                </td>
                <td>
                  <form method="get" action="{{ route('payments.invoice',$p->id) }}" >
                                      {{ csrf_field() }} 
                                      <div class="form-group">
                                      <input type="submit" class="btn btn-success btn-xs  " value="وه‌سل" >
                    
                                  </div>
                        </form>
                </td>
                
            </tr>
        @endforeach
        <tr>
        </tr>
    </tbody>
</table>
<div class="modal fade" id="insert-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" align="center"><b>New Payment</b></h4>
      </div>
      <div class="modal-body">
        <form action="{{ route('payments.store') }}" method="post">
                {{csrf_field()}}
          <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
          <div class="box-body">
            <div class="form-group">
              <label for="exampleInputEmail1">كڕیار</label> 
              <select class="form-control" name="customer_id" >
                    @foreach($customers as $c)
                      <option value="{{$c->id}}" >{{$c->name}}</option>
                  @endforeach
                  </select>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">بڕی پاره‌دان</label> 
              <input type="text" name="amount" class="form-control" placeholder="Amount">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">به‌روار</label> 
              <input type="date" name="date" class="form-control" placeholder="Date">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">تێبینی</label> 
              <input type="text" name="note" class="form-control" placeholder="Note">
            </div>
        </div>
                  <button type="submit" class="btn btn-primary">زیادكردن</button>

    </form>
</div>
</div>
</div>
</div>
@stop

resources/views/payments/edit.blade.php
@extends('adminlte::page')

@section('title', 'Hawras-Cars')

@section('content_header')
    <h1 class="text-center" >گۆرانكاری له‌ پاره‌دان</h1>
@stop
@section('content')
<div class="" id="insert-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" align="center"><b>Update Payment</b></h4>
      </div>
      <div class="modal-body">
        <form action="{{ route('payments.update',$payment->id) }}" method="post">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="PUT">

          <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
          <div class="box-body">
            <div class="form-group">
              <label for="exampleInputEmail1">Customer</label> 
              <select class="form-control" name="customer_id">
                    @foreach($customers as $c)
                      <option value="{{$c->id}}" {{ ( $c->id == $payment->customer_id) ? 'selected' : '' }} >{{$c->name}}</option>
                  @endforeach
                  </select>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Amount</label> 
              <input type="text" name="amount" class="form-control" placeholder="Amount" value="{{$payment->amount}}">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Date</label> 
              <input type="date" name="date" class="form-control" placeholder="Date" value="{{$payment->date}}">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Note</label> 
              <input type="text" name="note" class="form-control" placeholder="Note" value="{{$payment->note}}">
            </div>
        </div>
                  <button type="submit" class="btn btn-primary">گۆرین</button>

    </form>
</div>
</div>
</div>
</div>
@stop

resources/views/payments/invoice.blade.php
<style type="text/css">
        

body {
	 font-family: "Unikurd Jino";
	 width: 21cm;
  height: 29.5cm; 
  margin-left:auto;
  margin-right:auto;
  padding-left:1cm;
  padding-right:1cm;
  font-size: 15px;
  background: rgb(204,204,204); 
  -webkit-print-color-adjust: exact !important;
	}
page {
  background: white;
  display: block;
  margin: 0 auto;
  margin-bottom: 0.5cm;
  box-shadow: 0 0 0.5cm rgba(0,0,0,0.5);

}
page[size="A4"] {  
  width: 21cm;
  height: 29.7cm; 
  padding-bottom: 50px;
}
.logo{
	height:150px;
	width:200px;
}
.text-center{
	text-align: center;
}
.greybg{
	background-color:#C1D8CF;
	border:0px;
}
.textr{
	text-align: right;
}
.textl{
	text-align: left;
}
.textc{
	text-align: center;
}


table tr td {
	direction :rtl;
}

@media print
{     body.receipt { width: 58mm }
    .noprint, .noprint *
    {
        display: none !important;
        height:0px;
    }
    page {
  background: white;
  display: block;
  margin: 0 auto;
  margin-bottom: 0.5cm;
  box-shadow: 0 0 0cm rgba(0,0,0,0);

}
}

</style>
@php 
function convertNumberToWord($num = false)
{
    $num = str_replace(array(',', ' '), '' , trim($num));
    if(! $num) {
        return false;
    }
    $num = (int) $num;
    $words = array();
    $list1 = array('', 'یه‌ك', 'دوو', 'سێ', 'چوار', 'پێنج', 'شه‌ش', 'حه‌وت', 'هه‌شت', 'نۆ', 'ده‌', 'یانزه‌',
        'دوانزه‌', 'سیانزه‌', 'چوارده‌', 'پانزه‌', 'شانزه‌', 'حه‌ڤده‌', 'هه‌ژده‌', 'نۆزده‌'
    );
    $list2 = array('', 'ده‌', 'بیست', 'سی', 'چل', 'په‌نجا', 'شه‌ست', 'حه‌فتا', 'هه‌شتا', 'نه‌وه‌د', 'سه‌د');
    $list3 = array('', 'هه‌زار', 'ملیۆن', 'بلیۆن', 'ترلیۆن', 'quadrillion', 'quintillion', 'sextillion', 'septillion',
        'octillion', 'nonillion', 'decillion', 'undecillion', 'duodecillion', 'tredecillion', 'quattuordecillion',
        'quindecillion', 'sexdecillion', 'septendecillion', 'octodecillion', 'novemdecillion', 'vigintillion'
    );
    $num_length = strlen($num);
    $levels = (int) (($num_length + 2) / 3);
    $max_length = $levels * 3;
    $num = substr('00' . $num, -$max_length);
    $num_levels = str_split($num, 3);
    for ($i = 0; $i < count($num_levels); $i++) {
        $levels--;
        $hundreds = (int) ($num_levels[$i] / 100);
        $hundreds = ($hundreds ? ' ' . $list1[$hundreds] . ' سه‌د' . ' ' : '');
        $tens = (int) ($num_levels[$i] % 100);
        $singles = '';
        if ( $tens < 20 ) {
            $tens = ($tens ? ' ' . $list1[$tens] . ' ' : '' );
        } else {
            $tens = (int)($tens / 10);
            $tens = ' ' . $list2[$tens] . ' ';
            $singles = (int) ($num_levels[$i] % 10);
            $singles = ' ' . $list1[$singles] . ' ';
        }
        $words[] = $hundreds . $tens . $singles . ( ( $levels && ( int ) ( $num_levels[$i] ) ) ? ' ' . $list3[$levels] . ' ' : '' );
    } //end for loop
    $commas = count($words);
    if ($commas > 1) {
        $commas = $commas - 1;
    }
    return implode(' ', $words);
}
@endphp
<body onload="window.print()">
<page size="A4" >

	<button onclick="window.history.back();" class="noprint" style="background-color:red;width:100px;height:50px;border-radius:30px;font-weight:bold;font-size:17px;">Close</button>
  
  <table style="width:100%;">
    
      <div style="position:fixed; left:50px;top: 35px;">NO <div style="border:1px solid grey;border-radius: 5px;min-width: 100px !important;float: right;text-align: center;">{{$payment->id}}</div> </div>
      
    <tr>
      <td colspan="6"><img style="width:100%;" src="{{ asset('imgs/invoice.png') }}">
    </td>

    </tr>
    <tr>
      <td style="border:1px solid grey;border-radius: 5px;width:100px;text-align: center;">{{$payment->date}}</td>
      <td style="width:150px;"></td>
      <td style="border:1px solid grey;border-radius: 25px;font-weight:bold;" class="text-center">پسوله‌ی پاره‌ وه‌رگرتن</td>
      <td style="width:40px;"></td>
      <td  style="border:1px solid grey;text-align: center;width:50px; background-color:#C1D8CF;color:black; font-weight:bold;">دینار</td>
      <td  style="border:1px solid grey;text-align: left;">1000000</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td style="width:40px;"></td>
      <td style="border:1px solid grey;text-align: center;width:50px;background-color:#C1D8CF;color:black; font-weight:bold;" >دۆلار</td>
      <td style="border:1px solid grey;text-align: left;" >{{$payment->amount}}</td>
    </tr>
    <tr>
      <td colspan="5" style="border-bottom:1px dashed grey;">
        @php 
        echo convertNumberToWord($payment->amount).' دۆلار'; 
        @endphp
          
        </td>
      <td> بڕی </td>
    </tr>
    <tr>
      <td colspan="5" style="border-bottom:1px dashed grey;">{{$customer->name}}</td>
      <td>وه‌رگرت له‌ به‌ڕێز</td>
    </tr>
    <tr>
      <td colspan="5" style="border-bottom:1px dashed grey;">{{$payment->note}}</td>
      <td>بۆ مه‌به‌ستی</td>
    </tr>
    <tr>
      <td colspan="6" style="border-bottom: 2px solid black;height:20px;"></td>
    </tr>
    <tr>
      <td> </td>
      <td>كۆمپانیای هوراس: </td>
      <td colspan="2"></td>
      <td>ئیمزای پێده‌ر:</td>
      <td></td>
      
    </tr>
  </table>
  <br>
  <br>
  <hr>
  <table style="width:100%;margin-top:30px;">
    
      <div style="position:fixed; left:50px;top: 450px;">NO <div style="border:1px solid grey;border-radius: 5px;min-width: 100px !important;float: right;text-align: center;">{{$payment->id}}</div> </div>
      
    <tr>
      <td colspan="6"><img style="width:100%;" src="{{ asset('imgs/invoice.png') }}">
    </td>

    </tr>
    <tr>
      <td style="border:1px solid grey;border-radius: 5px;width:100px;text-align: center;">{{$payment->date}}</td>
      <td style="width:150px;"></td>
      <td style="border:1px solid grey;border-radius: 25px;font-weight:bold;" class="text-center">پسوله‌ی پاره‌ وه‌رگرتن</td>
      <td style="width:40px;"></td>
      <td  style="border:1px solid grey;text-align: center;width:50px; background-color:#C1D8CF;color:black; font-weight:bold;">دینار</td>
      <td  style="border:1px solid grey;text-align: left;">1000000</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td style="width:40px;"></td>
      <td style="border:1px solid grey;text-align: center;width:50px;background-color:#C1D8CF;color:black; font-weight:bold;" >دۆلار</td>
      <td style="border:1px solid grey;text-align: left;" >{{$payment->amount}}</td>
    </tr>
    <tr>
      <td colspan="5" style="border-bottom:1px dashed grey;">
        @php 
        echo convertNumberToWord($payment->amount).' دۆلار'; 
        @endphp
          
        </td>
      <td> بڕی </td>
    </tr>
    <tr>
      <td colspan="5" style="border-bottom:1px dashed grey;">{{$customer->name}}</td>
      <td>وه‌رگرت له‌ به‌ڕێز</td>
    </tr>
    <tr>
      <td colspan="5" style="border-bottom:1px dashed grey;">{{$payment->note}}</td>
      <td>بۆ مه‌به‌ستی</td>
    </tr>
    <tr>
      <td colspan="6" style="border-bottom: 2px solid black;height:20px;"></td>
    </tr>
    <tr>
      <td> </td>
      <td>كۆمپانیای هوراس: </td>
      <td colspan="2"></td>
      <td>ئیمزای پێده‌ر:</td>
      <td></td>
      
    </tr>
  </table>
</page>
</body>

resources/views/payments/payment.blade.php
@extends('adminlte::page')

@section('title', 'Hawras-Cars')

@section('content_header')
    <h1 class="text-center" >قه‌رزی كریاره‌كان</h1>
@stop
@section('content')
<style>
#wrapper2 {
    width: 80px;
    /*border: 1px solid black;*/
    overflow: hidden; /* will contain if #first is longer than #second */
}
#first {
    width: 40px;
    float:left; /* add this */
    /*border: 1px solid red;*/
}
#second {
  width: 40px;
    /*border: 1px solid green;*/
    overflow: hidden; /* if you don't want #second to wrap below #first */
}
</style>


	<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#insert-modal">
                <i class="fa fa-edit"></i>
              </button>
              <div class="col-md-4">
                <form class="form-horizontal pull-right" method="get" action="{{ route('payments.search') }}">
                    <div class="input-group">
                        <div class="input-group-btn">
                          <input type="submit" class="btn btn-danger" value="گه‌ڕان به‌ پێی ناوی كڕیار">
                        </div>
                        <!-- /btn-group -->
                        <select class="form-control" style="width: 100%; direction: rtl" name="search">
                            @foreach ($customers as $c)
                              @if (isset($selected) && $c->id==$selected)
                              <option value="{{ $c->id }}" selected>{{ $c->name }}</option> 
                                 @else 
                                 <option value="{{ $c->id }}">{{ $c->name }}</option> 
                              @endif
                            @endforeach
                          </select>
                      </div>

                </form>
              </div>
<table class="table table-respinsive table-hover table-fixed text-nowrap table-bordered">
	<thead>
		<tr class="row">
			<th>قه‌رز </th>
			<th>كۆی پاره‌دان $ </th>
			<th>كۆی نه‌قل و گومرگ </th>
			<th>كریار</th>
			<th>#</th>
			<th>Edit</th>
		</tr>
	</thead>
	<tbody>
		@foreach($gumrg as $g)
			<tr class="row">
				<td>
					@if(@isset($g->pay))
						$ {{ $g->total -$g->pay }}
					@else
					$ {{ $g->total }}
					@endif
				</td>
				<td>
					@if(@isset($g->pay))
					$ {{ $g->pay }}
					@else
						$ 0
					@endif
				</td>
				<td>
					$ {{ $g->total }}
				</td>
				<td>{{ $g->name }}
				</td>
				<td>{{ ++$i }}
				</td>
        <!--  -->
				<td><div id="wrapper2">
                        <div id="first">
                        	<form method="GET"action="{{ route('payments.show',$g->id) }}">
					        {{ csrf_field() }}
			                <button type="submit" class="btn btn-primary btn-circle btn-xs" data-toggle="modal" data-target="#edit-modal" > پاره‌دانه‌كان 
			                      <!-- <i class="fa fa-times"></i> -->
			                </button>
								    </form>
                        </div>
                        <div id="second">
                        	<!-- <form method="POST" action="/payments/{{$g->id}}">
					        {{ csrf_field() }}
					        {{ method_field('DELETE') }}

					           <button type="submit" class="btn btn-danger btn-circle btn-xs" onclick="return confirm('Are you sure?')">
					           	<i class="fa fa-times"></i>
								</button>
					    </form> -->
                        </div>
                    </div>
				</td>
				
			</tr>
		@endforeach
		<tr>
		</tr>
	</tbody>
</table>
<!-- Modals -->

<div class="modal fade" id="insert-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" align="center"><b>New Payment</b></h4>
      </div>
      <div class="modal-body">
        <form action="{{ route('payments.store') }}" method="post">
                {{csrf_field()}}
          <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
          <div class="box-body">
            <div class="form-group">
              <label for="exampleInputEmail1">Customer</label> 
              <select class="form-control" name="customer_id">
                    @foreach($customers as $c)
                      <option value="{{$c->id}}">{{$c->name}}</option>
                  @endforeach
                  </select>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Amount</label> 
              <input type="text" name="amount" class="form-control" placeholder="Amount">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Date</label> 
              <input type="date" name="date" class="form-control" placeholder="Date">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Note</label> 
              <input type="text" name="note" class="form-control" placeholder="Note">
            </div>
        </div>
                  <button type="submit" class="btn btn-primary">زیادكردن</button>

    </form>
</div>
</div>
</div>
</div>

@stop