routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('Auth/login');
});

// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::resource('/marz',"MarzController");
Route::resource('/balance',"BalanceController");
Route::resource('/gumrgpayment',"GumrgPaymenyController");

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

Route::get('/customers', 'CustomerController@index')->name('customers');
Route::get('/customers/search', 'CustomerController@search')->name('customers.search');
Route::get('/gumrg/search', 'GumrgController@search')->name('gumrgs.search');
Route::get('/gumrg/search_customer', 'GumrgController@search_customer')->name('gumrgs.search_customer');
Route::get('/gumrg/insertContract', 'GumrgController@insertContract')->name('gumrgs.insertContract');
Route::get('/gumrg/showContract', 'GumrgController@showContract')->name('gumrgs.showContract');
Route::get('/gumrg/action', 'GumrgController@action')->name('gumrg.action');
Route::get('/naql', 'GumrgController@naql')->name('naql');
// Route::get('/courses', 'courseController@store')->name('courses');
// Route::get('/courses', 'Courses@index')->name('home');
Route::resource('/customers',"CustomerController");
Route::resource('/gumrgs',"GumrgController");
Route::resource('/colors',"ColorController");
Route::resource('/cars',"CarsController");
Route::resource('/payments',"PaymentController");
Route::get('/payment', 'PaymentController@search')->name('payments.search');
Route::get('/invoice/{id}', 'PaymentController@invoice')->name('payments.invoice');
Route::resource('xawanQasa', 'XawanQasaController');
Route::get('/xawanQasas', 'XawanQasaController@search')->name('xawanQasa.search');
Route::resource('qasa', 'QasaController');
Route::get('/qasas', 'QasaController@search')->name('qasa.search');
// Route::resource('/courses',"courseController");
// Auth::routes();
Route::resource('roles', 'RoleController');
Route::resource('users', 'UserController');
Route::get('/users/action', 'UserController@action')->name('users.action');

Route::resource('permissions', 'PermissionController');

Route::get('/home', 'HomeController@index')->name('home');

app/Cars.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cars extends Model
{
    //
    public function Gumrg()
    {
    	return $this->hasMany('Gumrg');
    }
}

app/Http/Controllers/CarsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cars;

class CarsController extends Controller
{

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cars=Cars::paginate(10);
        $i=0;
        return view('cars.index',['cars'=>$cars,'i'=>$i]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $obj = new Cars();
        $obj->name=$request->input('name');
        $obj->company=$request->input('company');
        $obj->save();
        return redirect(route('cars.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $car = Cars::find($id);

        return view('cars.edit',['car'=>$car]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $obj=Cars::find($id);
        $obj->name= $request->input("name");
        $obj->company= $request->input("company");
        $obj->save();
        return redirect(route('cars.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cars=Cars::find($id);
        $cars->destroy($id);
        return redirect(route('cars.index'));
    }
}

resources/views/cars/edit.blade.php
@extends('adminlte::page')

@section('title', 'Hawras-Cars')

@section('content_header')
    <!-- <h1>Customer View</h1> -->
@stop

@section('content')
  
<div class="box">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box box-danger">
            <div class="box-header with-border">
              <h3 class="box-title">New Customer</h3>
            </div>
            <form action="{{ route('cars.update',$car->id) }}" method="post">
          {{csrf_field()}}
          <input type="hidden" name="_method" value="PUT">
            <div class="box-body">
              <div class="row">
                <div class="col-xs-3">
                        <input type="text" name="company" class="form-control" value="{{ $car->company }}">
                        </div>
                <div class="col-xs-2">
                  <input type="text" name="name" class="form-control" value="{{ $car->name }}">
                </div>
                <div class="col-xs-2">
                  <button type="submit" class="btn btn-block btn-lg btn-warning btn-lg">نوێكردنه‌وه‌</button>
                </div>
              </div>
            </div>
        </form>
            <!-- /.box-body -->
          </div>
            <!-- /.box-body -->
          </div>
@stop

resources/views/cars/index.blade.php
@extends('adminlte::page')

@section('title', 'Hawras-Cars')

@section('content_header')
    <!-- <h1>Customer View</h1> -->
@stop

@section('content')
  
<div class="box">
            <div class="box-header">
                <h1 style="text-align: center">به‌شی ئوتومبیله‌كان</h1>

            </div>
            <!-- /.box-header -->
            <div class="box box-danger">
            <div class="box-header with-border">
              
            </div>
            <form action="{{ route('cars.store') }}" method="post">
      	{{csrf_field()}}
            <div class="box-body">
              <div class="row">
                <div class="col-xs-3">
                        <input type="text" name="company" class="form-control" placeholder="كۆمپانیا">
                        </div>
                <div class="col-xs-2">
                  <input type="text" name="name" class="form-control" placeholder="ناو">
                </div>
                <div class="col-xs-2">
                  <button type="submit" class="btn btn-block btn-lg btn-success btn-lg">زیادكردن</button>
                </div>
              </div>
            </div>
        </form>
            <!-- /.box-body -->
          </div>
            <div class="box-body table-responsive no-padding table-bordered">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>ناو </th>
                  <th>كۆمپانیا</th>
                  <th>ده‌ستكاری كردن</th>
                  <th>سڕینه‌وه‌</th>
                </tr>
                 @foreach($cars as $c)
				    <tr>
				      <th scope="row">{{++$i}}</th>
				      <td>{{$c->name}}</td>
				      <td>{{$c->company}}</td>
				      <td><form method="GET"action="{{ route('cars.edit',$c->id) }}">
					        {{ csrf_field() }}

					        <div class="form-group">
					            <input type="submit" class="btn btn-warning btn-sm " value="Edit" >
		
					        </div>
                        </form></td>
                        <td><form method="post" action="{{ route('cars.destroy',$c->id) }}" >
                                {{ csrf_field() }} 
                                <input type="hidden" name="_method" value="DELETE"  >
                                <button class="btn btn-danger" onclick="return confirm('دڵنیایت له‌ سڕینه‌وه‌؟')">سڕینه‌وه‌</button>
                            </form></td>
				      </tr>
				      @endforeach

              </tbody></table>
            </div>
            <div class="text-center">
            {{ $cars->appends(Request::all())->render()}}
            </div>
            <!-- /.box-body -->
          </div>
@stop